#!/bin/bash
set -e

# initファイルをカレントディレクトリに変更
cd `dirname $0`
INIT_FILE_DIR=`pwd`

# =======================================================
# カラー文字
# =======================================================
# 赤背景、白文字で表示する
function red() {
	local message=$1
	printf "\e[37;41;5m$message\e[m\n"
}

# =======================================================
# 初期設定処理
# =======================================================

red "begin settings"

# このファイル(init)があるpathを指定する
echo "export MY_SHELL_ROOT_PATH=${INIT_FILE_DIR}" >> ~/.bashrc
echo "test -f $MY_SHELL_ROOT_PATH/setting/import_bashrc && source $MY_SHELL_ROOT_PATH/setting/import_bashrc" >> ~/.bashrc

red "end settings"
red "Please log in again!!!!!"