#!/bin/bash

# 参考リンク

# インポート
source $MY_SHELL_ROOT_PATH/setting/import

# =======================================================
#【 選択形式のセレクトメニュー】
# 
#   @return current_branch_res 現在のブランチ名
#
# [説明]
#   現在のブランチ名を返却する
#
# [使い方]
#   ```
#   current_branch
#   echo $current_branch_res
#   ```
# =======================================================

function current_branch() {
    if [ -n "$1" ]; then
        local project="-C "$1
    fi

    branch=`git $project branch | grep "*"`
    current=${branch/"* "/}
    current_branch_res=$current
}
