#!/bin/bash

# 参考リンク

# インポート

# =======================================================
#【 ファイルインポート】
#   @param $1 ファイル名
# 
# [説明]
#   関数をインポートする。
#
# [使い方]
#   ```
#   import some_function
#   ```
# =======================================================

# 処理中にエラーが出た場合に処理を停止する
set -e


source $MY_SHELL_ROOT_PATH/setting/profile

function import() {
	source $MY_SHELL_ROOT_PATH/support/$1
}
